{"tests": [{"data": {"status": "failure", "tool_id": "merge_heatmap_png", "time_seconds": 28.84514093399048, "inputs": {"sense_png": {"src": "hda", "id": "2891970512fa2d5a"}, "anti_png": {"src": "hda", "id": "5729865256bc2525"}}, "tool_version": "1.0.0", "output_problems": ["Job in error state.", "Job in error state."], "job": {"stdout": "", "job_stderr": "", "create_time": "2019-09-23T14:11:49.141441", "id": "54f2a3a23292eb07", "tool_stderr": "Traceback (most recent call last):\n  File \"/Users/pxk284/Desktop/Scratch/ChIP-QC-tools/merge_heatmap_png/merge_heatmap_png.py\", line 3, in <module>\n    from PIL import Image\nImportError: No module named PIL\n", "command_line": "python '/Users/pxk284/Desktop/Scratch/ChIP-QC-tools/merge_heatmap_png/merge_heatmap_png.py' '/private/var/folders/zz/zyxvpxvq6csfxvn_n0030flm00r3mx/T/tmpsXL2VF/files/6/f/d/dataset_6fd24723-1bd3-48ee-a72b-d99f0b743dcb.dat' '/private/var/folders/zz/zyxvpxvq6csfxvn_n0030flm00r3mx/T/tmpsXL2VF/files/2/6/1/dataset_2613f898-65ef-487c-b9db-c9f7a5cfc396.dat'", "exit_code": 1, "state": "error", "params": {"chromInfo": "\"/private/var/folders/zz/zyxvpxvq6csfxvn_n0030flm00r3mx/T/tmpsXL2VF/galaxy-dev/tool-data/shared/ucsc/chrom/?.len\"", "dbkey": "\"?\""}, "tool_stdout": "", "job_messages": [{"code_desc": "", "error_level": 3, "type": "exit_code", "exit_code": 1, "desc": "Fatal error: Exit code 1 ()"}], "tool_id": "merge_heatmap_png", "update_time": "2019-09-23T14:12:06.767635", "outputs": {"merged_heatmap": {"src": "hda", "id": "54f2a3a23292eb07", "uuid": "ff2fadd7-ebf2-4f65-a586-d199923f56aa"}}, "history_id": "2891970512fa2d5a", "job_metrics": [], "job_stdout": "", "inputs": {"sense_png": {"src": "hda", "id": "2891970512fa2d5a", "uuid": "6fd24723-1bd3-48ee-a72b-d99f0b743dcb"}, "anti_png": {"src": "hda", "id": "5729865256bc2525", "uuid": "2613f898-65ef-487c-b9db-c9f7a5cfc396"}}, "stderr": "Traceback (most recent call last):\n  File \"/Users/pxk284/Desktop/Scratch/ChIP-QC-tools/merge_heatmap_png/merge_heatmap_png.py\", line 3, in <module>\n    from PIL import Image\nImportError: No module named PIL\n", "model_class": "Job", "external_id": "5681", "user_email": "test@bx.psu.edu"}, "problem_log": "  File \"/Users/pxk284/anaconda2/lib/python2.7/unittest/case.py\", line 329, in run\n    testMethod()\n  File \"/private/var/folders/zz/zyxvpxvq6csfxvn_n0030flm00r3mx/T/tmpsXL2VF/galaxy-dev/test/functional/test_toolbox.py\", line 99, in test_tool\n    self.do_it(tool_version=tool_version, test_index=test_index)\n  File \"/private/var/folders/zz/zyxvpxvq6csfxvn_n0030flm00r3mx/T/tmpsXL2VF/galaxy-dev/test/functional/test_toolbox.py\", line 36, in do_it\n    verify_tool(tool_id, self.galaxy_interactor, resource_parameters=resource_parameters, test_index=test_index, tool_version=tool_version, register_job_data=register_job_data)\n  File \"/private/var/folders/zz/zyxvpxvq6csfxvn_n0030flm00r3mx/T/tmpsXL2VF/galaxy-dev/lib/galaxy/tools/verify/interactor.py\", line 790, in verify_tool\n    raise e\nJob in error state.\nJob in error state.\n-------------------- >> begin captured stdout << ---------------------\nCollecting package metadata: ...working... done\nSolving environment: ...working... done\n\n## Package Plan ##\n\n  environment location: /Users/pxk284/miniconda3/envs/mulled-v1-71c75af58e06045ad641775d7a888d3c1eb719379276865f8672cd54c8dcfc94\n\n  added / updated specs:\n    - pillow=5.4.0\n    - python=2.7.14\n    - zlib\n\n\nThe following NEW packages will be INSTALLED:\n\n  ca-certificates    conda-forge/osx-64::ca-certificates-2019.9.11-hecc5488_0\n  certifi            conda-forge/osx-64::certifi-2019.9.11-py27_0\n  freetype           conda-forge/osx-64::freetype-2.10.0-h24853df_1\n  jpeg               conda-forge/osx-64::jpeg-9c-h1de35cc_1001\n  libcxx             conda-forge/osx-64::libcxx-9.0.0-0\n  libcxxabi          conda-forge/osx-64::libcxxabi-9.0.0-0\n  libpng             conda-forge/osx-64::libpng-1.6.37-h2573ce8_0\n  libtiff            conda-forge/osx-64::libtiff-4.0.10-hd08fb8f_1003\n  lz4-c              conda-forge/osx-64::lz4-c-1.8.3-h6de7cb9_1001\n  ncurses            conda-forge/osx-64::ncurses-6.1-h0a44026_1002\n  olefile            conda-forge/noarch::olefile-0.46-py_0\n  openssl            conda-forge/osx-64::openssl-1.0.2r-h1de35cc_0\n  pillow             conda-forge/osx-64::pillow-5.4.0-py27hbddbef0_1000\n  pip                conda-forge/osx-64::pip-19.2.3-py27_0\n  python             conda-forge/osx-64::python-2.7.14-5\n  readline           conda-forge/osx-64::readline-7.0-hcfe32e1_1001\n  setuptools         conda-forge/osx-64::setuptools-41.2.0-py27_0\n  sqlite             conda-forge/osx-64::sqlite-3.20.1-0\n  tk                 conda-forge/osx-64::tk-8.6.9-h2573ce8_1003\n  wheel              conda-forge/osx-64::wheel-0.33.6-py27_0\n  xz                 conda-forge/osx-64::xz-5.2.4-h1de35cc_1001\n  zlib               conda-forge/osx-64::zlib-1.2.11-h01d97ff_1006\n  zstd               conda-forge/osx-64::zstd-1.4.0-ha9f0a20_0\n\n\nPreparing transaction: ...working... done\nVerifying transaction: ...working... done\nExecuting transaction: ...working... done\nProblem in history with id 2891970512fa2d5a - summary of history's datasets and jobs below.\n--------------------------------------\n| 1 - sense.png (HID - NAME) \n| Dataset State:\n|  ok\n| Dataset Blurb:\n|  5.4 KB\n| Dataset Info:\n|  uploaded png file\n| Peek:\n|  <table cellspacing=\"0\" cellpadding=\"3\"><tr><td>Image in png format</td></tr></table>\n| Dataset Job Standard Output:\n|  *Standard output was empty.*\n| Dataset Job Standard Error:\n|  *Standard error was empty.*\n|\n--------------------------------------\n| 2 - anti.png (HID - NAME) \n| Dataset State:\n|  ok\n| Dataset Blurb:\n|  5.4 KB\n| Dataset Info:\n|  uploaded png file\n| Peek:\n|  <table cellspacing=\"0\" cellpadding=\"3\"><tr><td>Image in png format</td></tr></table>\n| Dataset Job Standard Output:\n|  *Standard output was empty.*\n| Dataset Job Standard Error:\n|  *Standard error was empty.*\n|\n--------------------------------------\n| 3 - Merge Heatmap PNGs on data 2 and data 1 (HID - NAME) \n| Dataset State:\n|  error\n| Dataset Blurb:\n|  error\n| Dataset Info:\n|  Traceback (most recent call last):\n|  File \"/Users/pxk284/Desktop/Scratch/ChIP-QC-tools/merge_heatmap_png/merge_heatmap_png.py\", line 3, in <module>\n|  from PIL import Image\n|  ImportError: No module named PIL\n| Peek:\n|  None\n| Dataset Job Standard Output:\n|  *Standard output was empty.*\n| Dataset Job Standard Error:\n|  Traceback (most recent call last):\n|  File \"/Users/pxk284/Desktop/Scratch/ChIP-QC-tools/merge_heatmap_png/merge_heatmap_png.py\", line 3, in <module>\n|  from PIL import Image\n|  ImportError: No module named PIL\n|\n--------------------------------------\n| Job 54f2a3a23292eb07\n| State: \n|  error\n| Update Time:\n|  2019-09-23T14:12:06.767635\n| Create Time:\n|  2019-09-23T14:11:49.141441\n|\n--------------------------------------\n| Job 5729865256bc2525\n| State: \n|  ok\n| Update Time:\n|  2019-09-23T14:11:47.604174\n| Create Time:\n|  2019-09-23T14:11:41.268219\n|\n--------------------------------------\n| Job 2891970512fa2d5a\n| State: \n|  ok\n| Update Time:\n|  2019-09-23T14:11:40.669220\n| Create Time:\n|  2019-09-23T14:11:35.145778\n|\n--------------------------------------\nProblem in history with id 2891970512fa2d5a - summary of history's datasets and jobs below.\n--------------------------------------\n| 1 - sense.png (HID - NAME) \n| Dataset State:\n|  ok\n| Dataset Blurb:\n|  5.4 KB\n| Dataset Info:\n|  uploaded png file\n| Peek:\n|  <table cellspacing=\"0\" cellpadding=\"3\"><tr><td>Image in png format</td></tr></table>\n| Dataset Job Standard Output:\n|  *Standard output was empty.*\n| Dataset Job Standard Error:\n|  *Standard error was empty.*\n|\n--------------------------------------\n| 2 - anti.png (HID - NAME) \n| Dataset State:\n|  ok\n| Dataset Blurb:\n|  5.4 KB\n| Dataset Info:\n|  uploaded png file\n| Peek:\n|  <table cellspacing=\"0\" cellpadding=\"3\"><tr><td>Image in png format</td></tr></table>\n| Dataset Job Standard Output:\n|  *Standard output was empty.*\n| Dataset Job Standard Error:\n|  *Standard error was empty.*\n|\n--------------------------------------\n| 3 - Merge Heatmap PNGs on data 2 and data 1 (HID - NAME) \n| Dataset State:\n|  error\n| Dataset Blurb:\n|  error\n| Dataset Info:\n|  Traceback (most recent call last):\n|  File \"/Users/pxk284/Desktop/Scratch/ChIP-QC-tools/merge_heatmap_png/merge_heatmap_png.py\", line 3, in <module>\n|  from PIL import Image\n|  ImportError: No module named PIL\n| Peek:\n|  None\n| Dataset Job Standard Output:\n|  *Standard output was empty.*\n| Dataset Job Standard Error:\n|  Traceback (most recent call last):\n|  File \"/Users/pxk284/Desktop/Scratch/ChIP-QC-tools/merge_heatmap_png/merge_heatmap_png.py\", line 3, in <module>\n|  from PIL import Image\n|  ImportError: No module named PIL\n|\n--------------------------------------\n| Job 54f2a3a23292eb07\n| State: \n|  error\n| Update Time:\n|  2019-09-23T14:12:06.767635\n| Create Time:\n|  2019-09-23T14:11:49.141441\n|\n--------------------------------------\n| Job 5729865256bc2525\n| State: \n|  ok\n| Update Time:\n|  2019-09-23T14:11:47.604174\n| Create Time:\n|  2019-09-23T14:11:41.268219\n|\n--------------------------------------\n| Job 2891970512fa2d5a\n| State: \n|  ok\n| Update Time:\n|  2019-09-23T14:11:40.669220\n| Create Time:\n|  2019-09-23T14:11:35.145778\n|\n--------------------------------------\n\n--------------------- >> end captured stdout << ----------------------", "test_index": 0, "problem_type": "galaxy.tools.verify.interactor.JobOutputsError"}, "id": "functional.test_toolbox.TestForTool_merge_heatmap_png.test_tool_000000", "has_data": true}], "version": "0.1", "exit_code": 1, "summary": {"num_skips": 0, "num_errors": 0, "num_failures": 1, "num_tests": 1}}